services:
   app:
     image: 'order-service:latest'
     build:
       context: .
     ports:
       - 9090:9090
     container_name: orderService
     depends_on:
     - db
     environment:
       - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/order_db
       - SPRING_DATASOURCE_USERNAME=postgres
       - SPRING_DATASOURCE_PASSWORD=postgres
   db:
     image: 'postgres:13.1-alpine'
     container_name: postgres_db
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_DB=order_db
     ports:
       - 127.0.0.1:5432:5432