server:
  port: 9090

generateNumberService:
  url: http://127.0.0.1:9080/

spring:
  liquibase:
    change-log:
      classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/order_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver


spring-doc:
  swagger-ui:
    path: /oder-docs

logging:
   level:
     root: INFO
   file:
     name: src/main/resources/logs/application.log
